export const ADD_DISHES = 'ADD-DISHES';
export const DISHES_LOADING = ' DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
/** */
export const ADD_COMMENTS = 'ADD-COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENT = 'ADD_COMMENT';
/** */
export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';
export const LEADERS_LOADING = 'LEADERS_LOADING';
/** */
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';
/** */
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const POST_FAVORITE = 'POST_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

